### ISSUE TITLE
How???

### ISSUE THREAD

**Issue by onhate** [baselime/lambda-node-opentelemetry#46]
On the docs it says to just add a magic tag on my infrastructure and redirects me to here to see more details, here it says that I should not install it and just add a tag

How magically will my data be sent to the console with just a tag?? what do I need to install? is there a layer? what?? I am very confused.

**Comment by onhate** [comment]
My point is, I don't want magic introspection by the platform, I want to manually set the lambda layer and control it from my deployment instead of letting you manipulate my lambdas after I deploy them, ideally i don't want to deploy any cloudformation from your side, I just want to add the lambda layer and the api key and that's all, pretty much like the https://aws-otel.github.io/docs/getting-started/lambda does.

**Comment by Ankcorn** [comment]
Hey :) 

Thanks for the questions, it's not possible to just add the lambda layers and instrument node.js based lambda functions successfully in all scenarios. We also manually wrap the handler to create the span. This does require some magic. I agree this magic is not always good.

I'm working on consolidating our https://github.com/baselime/node-opentelemetry package with this one and as part of that there will be an example for manually instrumenting node.js based lambda functions.

**Comment by Carin-Quinlan** [comment]
It sounds like you're encountering some confusion regarding how to send data to the console using a magic tag in your infrastructure. Without specific context or details about the technology or service you're referring to, I can provide some general guidance on how this might work.

Magic Tag: The term "magic tag" suggests that you need to add a specific identifier or configuration to your infrastructure to enable data to be sent to the console. This could be something like a unique identifier or a configuration setting that triggers the data transfer.

No Installation Required: If the documentation explicitly states that you should not install anything and just add a tag, it suggests that the functionality might be achieved through configuration rather than installation of additional software or tools. This could mean that the infrastructure or service you're using already has the necessary components to handle the data transfer, and you just need to enable or configure them correctly.

Data Transfer Mechanism: Without more information, it's difficult to say exactly how the data will be sent to the console. However, common methods include using APIs, webhooks, or other integrations to push data from your infrastructure to the console. The "magic tag" you're instructed to add might include information needed to identify and route the data correctly.

Layers or Middleware: Depending on the architecture of your infrastructure and the console you're sending data to, there might be intermediary layers or middleware involved in handling the data transfer. These layers could handle tasks such as data formatting, authentication, or buffering before sending the data to the console.

To get more clarity on how this process works and what exactly you need to do, I would recommend referring to the documentation provided by the service or platform you're working with. Look for specific instructions on how to add the magic tag and any additional configuration steps required to enable data transfer to the console. If you're still unsure, reaching out to the support or community forums for the platform may also be helpful in getting clarification.

**Comment by onhate** [comment]
sounds like AI generated response to me...

**Comment by Ankcorn** [comment]
I have reported and deleted the spam.

Here are some examples of the otel tracer being configured without magic.

https://github.com/baselime/node-opentelemetry/blob/main/examples/serverless-otel/packages/functions/src/tracing.ts

This doesn't include the extension for 0 latency exporting but hopefully we can share some of the details for that soon.

I have also just refactored the lambda wrapper code https://github.com/baselime/node-opentelemetry/blob/main/src/lambda/index.ts

Hopefully this helps illustrate how you could do something better without the magic if you don't want it :) 

I'm going to close this issue because we have nothing to action on here but thanks for prompting us to be more transparent :)
